"""AI Chatbot / Financial Assistant service providing context-aware contract Q&A."""

import os
from typing import List, Tuple
import httpx

from app.intelligence.context_builder import build_contract_intelligence_context
from app.intelligence.chatbot.schemas import ChatRequest, ChatResponse
from app.intelligence.risk.service import risk_prediction_service
from app.intelligence.stress.schemas import StressTestRequest
from app.intelligence.stress.service import stress_test_service


class ChatbotService:
    """Financial Assistant service connecting structured context to Groq LLM or deterministic fallback."""

    def answer_question(self, contract_id: str, request: ChatRequest) -> ChatResponse:
        """Process user question against structured backend context."""
        ctx = build_contract_intelligence_context(contract_id)

        try:
            risk_res = risk_prediction_service.evaluate_contract_risk(contract_id)
            risk_summary = f"Category: {risk_res.risk_category}, Default Prob: {risk_res.default_probability_percent}%, Expected Loss: ₹{risk_res.expected_loss:,.2f}"
        except Exception:
            risk_summary = "Risk analysis not evaluated."

        groq_key = os.getenv("GROQ_API_KEY", "").strip()

        if groq_key:
            try:
                system_prompt = (
                    "You are a financial contract assistant. Only answer using the supplied contract context.\n"
                    "Do not invent contract values.\n"
                    "Do not claim that money moved on-chain unless the blockchain data explicitly confirms a token transfer.\n"
                    "Distinguish:\n"
                    "- expected ACTUS schedule\n"
                    "- blockchain recorded activity\n"
                    "- financial reconciliation\n"
                    "- AI risk prediction\n"
                    "- blockchain status\n\n"
                    "When information is unavailable, say so. Risk predictions are model outputs, not guarantees."
                )

                user_prompt = (
                    f"CONTRACT CONTEXT:\n"
                    f"Contract ID: {ctx['contract']['contract_id']}\n"
                    f"Principal: ₹{ctx['contract']['principal']:,.2f} {ctx['contract']['currency']}\n"
                    f"Interest Rate: {ctx['contract']['annual_interest_rate']}%\n"
                    f"Dates: {ctx['contract']['start_date']} to {ctx['contract']['maturity_date']}\n"
                    f"ACTUS Type: {ctx['actus']['contract_type']}\n"
                    f"Expected Total Schedule: ₹{ctx['reconciliation']['expected_total']:,.2f} across {ctx['reconciliation']['expected_payment_count']} payments\n"
                    f"Recorded Paid On-Chain: ₹{ctx['reconciliation']['actual_total']:,.2f} across {ctx['reconciliation']['actual_payment_count']} payments\n"
                    f"Net Amount Variance: ₹{ctx['reconciliation']['net_variance']:,.2f}\n"
                    f"Unpaid Payments: {ctx['reconciliation']['unpaid_payment_count']}\n"
                    f"Overdue Payments: {ctx['reconciliation']['overdue_payment_count']}\n"
                    f"Reconciliation Status: {ctx['reconciliation']['overall_status']}\n"
                    f"Integrity Matched: {ctx['reconciliation']['hash_integrity_matched']}\n"
                    f"AI Risk Profile: {risk_summary}\n\n"
                    f"USER QUESTION: {request.message}"
                )

                response = httpx.post(
                    "https://api.groq.com/openai/v1/chat/completions",
                    headers={
                        "Authorization": f"Bearer {groq_key}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "model": "llama-3.3-70b-versatile",
                        "messages": [
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt},
                        ],
                        "temperature": 0.2,
                    },
                    timeout=10.0,
                )

                if response.status_code == 200:
                    answer_text = response.json()["choices"][0]["message"]["content"]
                    return ChatResponse(
                        contract_id=contract_id,
                        answer=answer_text,
                        sources=["reconciliation", "actus_schedule", "blockchain_activity", "risk_prediction"],
                        available=True,
                        message="Answer generated by Groq LLM Assistant.",
                    )
            except Exception:
                pass

        # Deterministic Fallback Responder for common demo questions
        answer, sources = self._fallback_answer(ctx, risk_summary, contract_id, request.message)

        return ChatResponse(
            contract_id=contract_id,
            answer=f"AI assistant is not configured; showing data-based answer.\n\n{answer}",
            sources=sources,
            available=False,
            message="Groq API key not configured; displaying data-backed deterministic response.",
        )

    def _fallback_answer(
        self, ctx: dict, risk_summary: str, contract_id: str, question: str
    ) -> Tuple[str, List[str]]:
        q = question.lower()
        recon = ctx["reconciliation"]
        contract = ctx["contract"]

        if "deviation" in q or "status" in q or "why" in q:
            return (
                f"The contract status is currently **{recon['overall_status']}**. "
                f"Out of {recon['expected_payment_count']} expected scheduled payments totaling ₹{recon['expected_total']:,.2f}, "
                f"{recon['actual_payment_count']} payments totaling ₹{recon['actual_total']:,.2f} have been recorded on MST Blockchain. "
                f"There are currently {recon['unpaid_payment_count']} unpaid scheduled payments, resulting in a net variance of ₹{recon['net_variance']:,.2f}.",
                ["reconciliation", "blockchain_activity"],
            )

        if "expected" in q or "schedule" in q or "total" in q:
            return (
                f"The expected ACTUS schedule requires **{recon['expected_payment_count']} payments** "
                f"totaling **₹{recon['expected_total']:,.2f}** over the contract term from {contract['start_date']} to {contract['maturity_date']}.",
                ["actus_schedule"],
            )

        if "recorded" in q or "actual" in q or "on-chain" in q or "paid" in q:
            return (
                f"MST Blockchain has recorded **{recon['actual_payment_count']} payment event(s)** "
                f"totaling **₹{recon['actual_total']:,.2f}**. Smart contract status is **{recon['blockchain_status']}** at address `{recon['blockchain_address']}`.",
                ["blockchain_activity"],
            )

        if "risk" in q or "default" in q or "loss" in q:
            return (
                f"The AI Risk Prediction for this contract evaluates to: **{risk_summary}**. "
                f"This prediction is calculated from 22+ quantitative contract features including principal, rate, duration, and payment variances.",
                ["risk_prediction"],
            )

        if "stress" in q or "rate" in q or "increase" in q:
            try:
                st_res = stress_test_service.run_stress_test(contract_id, StressTestRequest(rate_shock_percent=3.0))
                return (
                    f"Under a +3.0% interest rate shock, total interest increases from ₹{st_res.base_case.total_interest:,.2f} to ₹{st_res.stressed_case.total_interest:,.2f} "
                    f"(an additional ₹{st_res.difference.additional_interest:,.2f} or {st_res.difference.percentage_increase_in_interest}% increase). "
                    f"Risk impact: {st_res.risk_impact['summary']}",
                    ["stress_testing"],
                )
            except Exception:
                pass

        if "suggest" in q or "terms" in q or "safer" in q or "negotiate" in q:
            return (
                f"To reduce lender risk for this {contract['annual_interest_rate']}% annuity contract, recommended term modifications include: "
                f"1) Adjusting annual interest rate to {contract['annual_interest_rate'] + 1.5}%, "
                f"2) Requiring a 15% collateral reserve deposit, and "
                f"3) Mandating automated monthly direct debit.",
                ["negotiation_agent"],
            )

        if "integrity" in q or "hash" in q:
            matched_str = "MATCHED" if recon["hash_integrity_matched"] else "MISMATCH / UNVERIFIED"
            return (
                f"Off-chain Phase 6 SHA-256 integrity hash verification status is **{matched_str}** against on-chain smart contract `actusHash`.",
                ["hash_integrity"],
            )

        return (
            f"Contract Summary: ID {contract['contract_id']}, Principal ₹{contract['principal']:,.2f}, Rate {contract['annual_interest_rate']}%, "
            f"Status {recon['overall_status']}. Expected payments: {recon['expected_payment_count']} (₹{recon['expected_total']:,.2f}), "
            f"Recorded on-chain: {recon['actual_payment_count']} (₹{recon['actual_total']:,.2f}).",
            ["reconciliation"],
        )


chatbot_service = ChatbotService()
