"""ABI definition for Person 2's FinancialContractV2 Solidity smart contract."""

FINANCIAL_CONTRACT_V2_ABI = [
    {
        "inputs": [],
        "name": "lender",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "borrower",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "principal",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "interestRateBps",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "maturityDate",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "actusHash",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "status",
        "outputs": [{"internalType": "enum FinancialContractV2.Status", "name": "", "type": "uint8"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalPaid",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "activateContract",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "amount", "type": "uint256"}],
        "name": "recordPayment",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "markDelinquent",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getContractDetails",
        "outputs": [
            {"internalType": "address", "name": "_lender", "type": "address"},
            {"internalType": "address", "name": "_borrower", "type": "address"},
            {"internalType": "uint256", "name": "_principal", "type": "uint256"},
            {"internalType": "uint256", "name": "_interestRateBps", "type": "uint256"},
            {"internalType": "uint256", "name": "_maturityDate", "type": "uint256"},
            {"internalType": "bytes32", "name": "_actusHash", "type": "bytes32"},
            {"internalType": "uint8", "name": "_status", "type": "uint8"},
            {"internalType": "uint256", "name": "_totalPaid", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "lender", "type": "address"},
            {"indexed": True, "name": "borrower", "type": "address"},
            {"indexed": False, "name": "principal", "type": "uint256"},
            {"indexed": False, "name": "interestRateBps", "type": "uint256"},
            {"indexed": False, "name": "maturityDate", "type": "uint256"},
            {"indexed": False, "name": "actusHash", "type": "bytes32"},
        ],
        "name": "ContractCreated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [],
        "name": "ContractActivated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "name": "amount", "type": "uint256"},
            {"indexed": False, "name": "paymentDate", "type": "uint256"},
            {"indexed": False, "name": "totalPaid", "type": "uint256"},
        ],
        "name": "PaymentRecorded",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [],
        "name": "ContractCompleted",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [],
        "name": "ContractMarkedDelinquent",
        "type": "event",
    },
]
